version: "3"  

services: 

  namenode: 

    image: apache/hadoop:3.4.3 

    container_name: namenode 

    hostname: namenode 

    command: ["hdfs", "namenode"] 

    ports: 

      - "9870:9870" 

      - "9000:9000" 

    environment: 

      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name" 

    env_file: 

      - ./hadoop.env 

  

  datanode: 

    image: apache/hadoop:3.4.3 

    container_name: datanode 

    command: ["hdfs", "datanode"] 

    depends_on: 

      - namenode 

    env_file: 

      - ./hadoop.env 

  

  resourcemanager: 

    image: apache/hadoop:3.4.3 

    container_name: resourcemanager 

    hostname: resourcemanager 

    command: ["yarn", "resourcemanager"] 

    ports: 

      - "8088:8088" 

    depends_on: 

      - namenode 

      - datanode 

    env_file: 

      - ./hadoop.env 

  

  nodemanager: 

    image: apache/hadoop:3.4.3 

    container_name: nodemanager 

    command: ["yarn", "nodemanager"] 

    depends_on: 

      - resourcemanager 

    env_file: 

      - ./hadoop.env 
